AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates a CoOps Orchestrator IAM role that can dynamically create, update, and delete project-specific executor roles.

Parameters:
  IacRoleArn:
    Type: String
    Description: The full ARN of the CoOps IAM role allowed to assume this role (e.g., arn:aws:iam::017820667206:role/coops-12345-xxxx-iac-role)
  UniqueId:
    Type: String
    Description: A unique identifier for this deployment (e.g., 12345)
  ExternalId:
    Type: String
    Description: The external ID required for trust (e.g., 123e4567-e89b-12d3-a456-426614174000)

Resources:
  OrchestratorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub coops-orchestrator-${UniqueId}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref IacRoleArn
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - eks.amazonaws.com
                - ecs.amazonaws.com
                - lambda.amazonaws.com
                - pods.eks.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:TagSession
      Policies:
        - PolicyName: OrchestratorIAMManagementPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:UpdateRole
                  - iam:GetRole
                  - iam:ListRoles
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:PassRole
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:ListRoleTags
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/coops-executor-*-role
              - Effect: Allow
                Action:
                  - iam:CreatePolicy
                  - iam:DeletePolicy
                  - iam:GetPolicy
                  - iam:ListPolicies
                  - iam:ListPolicyVersions
                  - iam:CreatePolicyVersion
                  - iam:DeletePolicyVersion
                  - iam:GetPolicyVersion
                  - iam:ListPolicyTags
                  - iam:TagPolicy
                  - iam:UntagPolicy
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:policy/coops-executor-*-policy
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/coops-executor-*-role
Outputs:
  OrchestratorRoleArn:
    Description: ARN of the Orchestrator role
    Value: !GetAtt OrchestratorRole.Arn
