{{- if gt (len .Values.envSecrets ) 0 }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  provider:
    {{- if eq .Values.cloudProvider "aws" }}
    aws:
      service: SecretsManager
      region: {{ .Values.envRegion }}
    {{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: {{ include "deployment.fullname" . }}
  target:
    name: {{ include "deployment.fullname" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.envSecrets }}
    {{- range $key, $value := . }}
    - secretKey: {{ $key | lower }}
      remoteRef:
        key: {{ $value | quote }}
    {{- end }}
    {{- end }}
{{- end }}
