name: Scan Secrets using Gitleaks

on:
  workflow_call:
  pull_request:

jobs:
  secret-scan:
    runs-on:
      group: self-hosted
      labels: [linux, x86_64]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: download gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.27.2/gitleaks_8.27.2_linux_x64.tar.gz | tar zx
          mv gitleaks /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks
      
      - name: run scan
        run: |
          gitleaks detect . --no-git --verbose